kibana_host: 0.0.0.0
kibana_port: 5601
kibana_package_url: https://artifacts.elastic.co/downloads/kibana/kibana-5.6.3-x86_64.rpm
kibana_xpack_package_url: https://artifacts.elastic.co/downloads/packs/x-pack/x-pack-5.6.3.zip
kibana_elasticsearch_url: http://localhost:9200
kibana_elasticsearch_username: user
kibana_elasticsearch_password: pass