---
- hosts: elasticsearch_nodes
  become: yes
  gather_facts: yes

  roles:
    - { role: elastic.elasticsearch,
        es_version: 5.6.3,
        es_instance_name: "{{ inventory_hostname }}",
        es_data_dirs: "/opt/elasticsearch/data",
        es_log_dir: "/opt/elasticsearch/logs",
        es_config: {
          node.name: "{{ inventory_hostname }}",
          cluster.name: "falcon",
          network.host: "{{ inventory_hostname }}, _local_",
          discovery.zen.ping.unicast.hosts: "{{ ansible_play_hosts | join(', ') }}",
          discovery.zen.minimum_master_nodes: 2,
          http.port: 9200,
          transport.tcp.port: 9300,
          bootstrap.memory_lock: false
        }
      }
  vars:
    es_heap_size: "512m"
    es_enable_xpack: true,
    es_plugins:
      - plugin: mapper-attachments
    es_xpack_features:
      - security
    es_api_basic_auth_username: elastic
    es_api_basic_auth_password: changeme
    es_users:
      native:
        dataloader:
          password: mimacom
          roles:
            - dataloader
        edorasone:
          password: loveyourwork
          roles:
            - edorasone
    es_roles:
      native:
        dataloader:
          cluster:
            - manage_index_templates
            - transport_client
          indices:
            - names: 'dl.*'
              privileges:
                - all
        edorasone:
          cluster:
            - manage_index_templates
            - transport_client
          indices:
            - names: 'edo.*'
              privileges:
                - all
            - names: 'dl.*'
              privileges:
                - read


# TODO
# change default users password, or disable them