---
- hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: update host file
      blockinfile:
        path: /etc/hosts
        block: |
          10.0.15.21 node1
          10.0.15.22 node2
          10.0.15.23 node3

