---
- hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: update host file
      blockinfile:
        path: /etc/hosts
        block: |
          172.28.128.11 node1
          172.28.128.12 node2
          172.28.128.13 node3

