- hosts: kibana_nodes
  roles:
    - role: sansible.kibana
      kibana:
        host: 0.0.0.0
        install_dir: /usr/share/kibana/
        tarball: kibana-5.6.3-linux-x86_64
        download_base_url: https://artifacts.elastic.co/downloads/kibana/
        version: 5.6.3
        port: 5601
        plugins: []
        elasticsearch:
          host: node1
          port: 9200

# currently the x-pack was installed manually on it
# /usr/share/kibana/bin/kibana-plugin install x-pack

# add possibility to download artifacts without internet
# install the with ansible



