- hosts: kibana_nodes
  roles:
    - role: sansible.kibana
      kibana:
        host: kibana
        install_dir: /usr/share/kibana/
        tarball: kibana-5.6.3-linux-x86_64
        download_base_url: https://artifacts.elastic.co/downloads/kibana/
        version: 5.6.3
        port: 5601
        plugins: []
        elasticsearch:
          host: node1
          port: 9200

# currently the x-pack was installed manually on it
# not sure how to expose the service to the host